### ISSUE TITLE
Installation unter Contao 4.13 nicht möglich

### ISSUE THREAD

**Issue by Schmidty2** [markocupic/resource-reservation-bundle#31]
Die Version 4.0.5 lässt sich nicht unter Contao 4.13.12 installieren, weder unter PHP 7.4 noch unter PHP 8.1.
Das händische Ändern der Versionsnummer im Contao-Manger ändert nichts.

Ich bin mir nicht sicher, müsste es nicht "contao/core-bundle": ">=4.11", statt "contao/core-bundle": "^4.11" heißen, oder ist die Erweiterung nur für die Version 4.11 freigegeben?

![grafik](https://user-images.githubusercontent.com/2067428/195781561-96da9ca2-de72-4c67-9e7b-b24fe80937cc.png)

Danke fürs fixen :-)

**Comment by markocupic** [comment]
Kann ich nicht reproduzieren. Soeben getestet unter PHP 8.1 und Contao 4.13.12.
Die aktuellste Version 4.0.5 ist freigeben für contao/core-bundle ^4.13, was soviel bedeutet wie contao/core-bundle >= 4.13 und < 5.0. Für Contao 4.11 ist die Erweiterung nicht freigeben. 

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1525166/195917026-aa033238-118e-4e55-9085-70c85f42caad.png">

**Comment by Schmidty2** [comment]
Jetzt läuft die Installation durch, Danke für die Rückmeldung
